spring:
  application:
    name: aggregator-microservice
  config:
    import: "optional:configserver:http://config-server-microservice:8080"
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
