spring:
  application:
    name: aggregator-microservice
  config:
    import: "optional:configserver:http://localhost:8080"
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
