version: "3"

services:
  humidity:
    image: humidity-microservice-jib:0.0.1-SNAPSHOT
    restart: on-failure
    build:
      context: ./microservices/humidity-microservice
    ports:
      - "8081:8081"

  temperature:
    image: temperature-microservice-jib:0.0.1-SNAPSHOT
    restart: on-failure
    build:
      context: ./microservices/temperature-microservice
    ports:
      - "8082:8082"

  aggregator:
    image: aggregator-microservice-jib:0.0.1-SNAPSHOT
    restart: on-failure
    build:
      context: ./microservices/aggregator-microservice
    ports:
      - "8000:8000"

networks:
  default:
    name: local-net
